pandoc_version: 1.19.2.1

env:
  global:
    secure: IRk28GxhmW7Wa9mA78QY4MeWgvYa2b47SNX8GQH2CW2VAX2k7wQlBt97QtiKgfVz6IVEnFgknD6Z2+INpNn4hqxalkvLzky5GLH3Dec+D5TtCWmZIIv8jCf2dAV2+b6zBCOSsLIQezZSZc3rGj8mQ9Sczg/agCeFPdVuyl0Vd247/f312gE7OeF5whazTS/fLnh1mqDP0OYzpXA/r5pyY28uI8YuQ4PyfE1wVlvbrMf9/OQNLX2JhLBk6SagBiAqtZsS1KRfahraKFmzKbnyRawWVwSvQoCJSbVO0EELBuw5EHkA379Xe9Ego1qqG+fCrYeUQmNFyij0obO9sJXX+IcLv36mnj0mdJlsSMdP6VAf4nUHbjKA2g1wfUQAMwidV6KPuq/YYjib+an/++Y0nKE0lnS5SupVZVAxbTvb+4kgoMV1l/Zbc7oXVLm3ioFzPiVrXRchbg4q2dgQQoijExfxNEtu5xIfAkLZjrj0JBwCYHNsDFfzCwev8kU4cOfNeDrOqG9x1YNottoETgMuEcnViSgpLqkfMd3XMnaIYmeCBmm644dEehoWySH/KVptPGZ1JuUL0/aDjETi8ZQP1UpaQB5uGOg49MZGyWCe9X+GHODJMxIrsweH3Nf9ohOSzwGJIXHcYxmEMP3N4h1nxs5NlvGW0T1wb9LpGeFGkWs=

before_script:
  - chmod +x ./_build.sh
#  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
#  - ./_deploy.sh
